### ISSUE TITLE
Reading data in pandas dataframes

### ISSUE THREAD

**Issue by JonL001** [jmc856/mysportsfeeds-python#5]
I used the following command to get data:
`output = msf.msf_get_data(league='nba',season='2016-regular',feed='cumulative_player_stats',format='csv')`

It saves a .csv file in a folder called results, I then upload that file using:
`df = pd.read_csv('cumulative_player_stats-nba-2016-regular.csv')`

However, this reads the data in with only 1 column - no matter what I use as a delimiter nothing helps. I went to excel and manually set a comma delimiter, but this resulted in some columns being misaligned (there are sometimes commas in birth city or birth country).  Is there a simple way to read the .csv (or .json or any type) into a usable Pandas DataFrame? Thanks!

@jmc856 Appreciate your help!
@prcutler I'm a fan of your work, any ideas?
@bradbarkhouse I didn't see a way to post this issue on your page so I put it here, thank you!

**Comment by prcutler** [comment]
No idea - I'm fairly new to Python and have never used Pandas

**Comment by jmc856** [comment]
JonL001, 

Can you please show some code examples?  Example of what the result.csv file looks like?  It has been awhile since I touched this.

**Comment by JonL001** [comment]
Thanks for your response! Here's some example code:

`msf = MySportsFeeds(version="1.2")`
`msf.authenticate('username', 'password')`
`output = msf.msf_get_data(league='nba',season='2016-2017-regular',feed='player_gamelogs',format='csv',player='stephen-curry')`

If you use `steph = pd.read_csv('player_gamelogs-nba-2016-2017-regular.csv',sep=',')` it doesn't properly read in the file because under the birth city column, American players' birth cities are listed like 'Akron, OH' which throws off the comma delimiter. Thus, everything after birth city is shifted to the right. There are also other issues like quotes and extra spaces in the column names, random # symbols, and other things that can be cleaned up using pandas or done in excel. But I was wondering if there is something out there already that addresses these issues. 

Also, I'm trying to combine player game logs for every player, but if I use 
`output = msf.msf_get_data(league='nba',season='2016-2017-regular',feed='player_gamelogs',format='csv')` I get a 400 error
>400 error: Indicates that some part of the request is malformed.

Also,  
`output = msf.msf_get_data(league='nba',season='2016-2017-regular',feed='game_boxscore',format='csv')` gets a 404 error (no explanation for 404 errors).

Is there a way to get the game logs for every player for every game in a season? Thank you so much for your help!

**Comment by bradbarkhouse** [comment]
That's interesting about the comma-delimiter @JonL001 .  I don't know much about Pandas, but when I open the CSV in OpenOffice Calc (similar to Excel), I don't see the same issue.  Maybe there's a special way to specify the delimiter, and to ignore the "#" prefix in the column headings?

The 400 response is b/c the player_gamelogs feed requires at least one of: player, team, or game params.  That's by design, as otherwise the underlying dataset would be HUGE and would potentially cause performance problems.  So you'll need to break it up into several requests.

The 404 response for the game_boxscore feed is b/c you didn't specify the required gameid param to identify the game requested.

Hope that helps!

**Comment by JonL001** [comment]
Thanks everyone for all of your comments and insight, it was all incredibly helpful. I was able to create a function that calls each team's player logs for the season, cleans them up, and then combines them into one database for analysis. I learned a ton in the process and would be happy to share the code if anyone is interested!
